### PR TITLE
Initialise react-axe only once and not in every file with react

### PR DESCRIPTION
**Pull request by badtant**

### CODE REVIEW

**Comment by dylanb** [comment]
The `getCommonParent` function is supposed to find a common parent and will traverse up the DOM tree all the way to the HTML node the very first time it does the analysis. If you build the example, you will see that it checks the entire page on the first analysis and then not after that.

This change breaks that. I did not detect this previously because I was testing on the version that had undone the change.

So the question becomes: what are you doing in your project so that the entire document is not being analyzed?

**Comment by badtant** [comment]
Hmm, I see. 
Logging what getCommonParent gets:
Example: [body, p, p, p, p, div]
My app: [body]

My app i universal (isomorphic). Is that an issue?

**Comment by badtant** [comment]
Tried it with one of my client only apps and gets only body there too...
Running React 15.3.0 on both of them.

**Comment by badtant** [comment]
Hmm, maybe I need to set the Debouncing higher. Will test first thing tomorrow

**Comment by badtant** [comment]
Nope, that didn't help...
So, I added logging to see if I come into this function and I don't so I guess that causes the proplem.
`r.createClass = function (...args) {}`

**Comment by badtant** [comment]
So, I've updated the example to be more like a real app where each component is in a different file. Each of them require react and maybe that is where to problem is because now I get the same result from the example as I do with my projects.

**Comment by badtant** [comment]
react-a11y seem to hook into react correctly (though I thinks their checks are not as good as axe) so maybe that is something to look at?

**Comment by dylanb** [comment]
The problem is that calls to react-axe need to be made in each file. Look at https://github.com/dylanb/react-axe/pull/9

**Comment by badtant** [comment]
Ahh, I see. Didn't understand that from the documentation. I'm afraid that will be impossible to maintain for larger projects.

With react-a11y I can initialize it at the top level. Would be a great feature for react-axe.

**Comment by badtant** [comment]
I've been spending a few hours to look at react-a11y. I've pushed a base for this which seems to work OK but I'm not 100% sure of what I'm doing :)

If you wanna take a look at it...

**Comment by dylanb** [comment]
@badtant This is an interesting approach because it might work with ES6 React code too. I will test it. However, I don't see how this fixes the basic problem of needing to make calls within each file. Have you tested that?

**Comment by dylanb** [comment]
@badtant this works with ES6 components too - awesome!! Can you delete the old index.js file and then I'll merge.

**Comment by dylanb** [comment]
@marcysutton you might want to pull this branch and integrate this into your React Rally presentation

**Comment by marcysutton** [comment]
Totally, this looks awesome. Great work!

**Comment by badtant** [comment]
@dylanb yeah, I'm using es6 in my projects and it works good. I've deleted the file :)

**Comment by dylanb** [comment]
@badtant I made a couple of small changes to make your implementation more robust https://github.com/dylanb/react-axe/commit/caad72421840bc84a81d757044df2efd848a3fa6. This is now published as 2.0.1

**Pull request merged**
