### PR TITLE
Don't use rest parameters to prevent errors in Safari 9

### PR DESCRIPTION
**Pull request by junyper**
Safari 9 doesn't support rest parameters :(

### CODE REVIEW

**Comment by dylanb** [comment]
@junyper what about babelifying instead of changing the source code?

**Comment by junyper** [comment]
I thought about that, but these changes didn't seem like a big deal.

**Comment by dylanb** [comment]
@junyper does this mean that the log APIs we are using also work in Safari? If so, could you update the documentation to state that it works in Safari and Chrome.

**Comment by badtant** [comment]
I can confirm that this works in safari and also i firefox (although not as pretty output)

**Comment by junyper** [comment]
@dylanb I updated the README to note Safari and Firefox support. Let me know if you're ok with the wording.

**Comment by dylanb** [comment]
@junyper Thank you for the contribution

**Pull request merged**
