### PR TITLE
Add support for optional config to axe-core

### PR DESCRIPTION
**Pull request by badtant**

### CODE REVIEW

**Comment by dylanb** [comment]
Thank you for the contribution!!

**Comment by badtant** [comment]
When will there be a new release? Would be great with a new one with my 3 PRs.

**Comment by dylanb** [comment]
I wanted to wait for confirmation from @reintroducing to make sure this https://github.com/dylanb/react-axe/issues/3 problem is fixed before publishing - that ok with you?

**Comment by reintroducing** [comment]
Sorry guys, I'm on vacation til Weds so won't get around to it til probably Thursday at earliest.  You could test with the code I provided and see if it works if you want an answer sooner :\

**Pull request merged**
